# Prod environment
variables:
  # Global
  ap_vm_image: Canonical:0001-com-ubuntu-server-jammy:22_04-lts-gen2:latest

  namespace: aionazml # Updated namespace
  postfix: 001 # Updated postfix
  location: eastus # Updated location

  environment: prod
  enable_aml_computecluster: true
  enable_aml_secure_workspace: true
  enable_monitoring: false

  # Azure DevOps
  ado_service_connection_rg: Azure-ARM-Prod
  ado_service_connection_aml_ws: Azure-ARM-Prod

  # For pipeline reference
  resource_group: aionaz
  aml_workspace: aionazml
